server {
    listen 80;
    server_name _;

    # Le decimos dónde están los archivos de React
    root /usr/share/nginx/html;
    index index.html;

    # Evita el error 404
    location / {
        try_files $uri $uri/ /index.html;
    }
}
